//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesMvcAngular.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.InvoiceHeaders = new HashSet<InvoiceHeader>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<InvoiceHeader> InvoiceHeaders { get; set; }
    }
}
